spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
mybatis:
  configuration:
    map-underscore-to-camel-case: true
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: ourchat的接口文档
  try-host: http://localhost:${server.port}
netty:
  path: /websocket



