spring:
  datasource:
    username: root
    password: 54188
    url: jdbc:mysql://localhost:3306/chat?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ourchat
    # redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
        min-idle: 2
    timeout: 6000
  mail:
#    Gmail邮箱
#    host: smtp.gmail.com
#    username: zgl4131025@gmail.com
#    password: *************
#    protocol: smtp
#    properties.mail.smtp.auth: true
#    properties.mail.smtp.port: 465
#    properties.mail.display.sendmail: Javen
#    properties.mail.display.sendname: Spring Boot Guide Email
#    properties.mail.smtp.starttls.enable: true
#    properties.mail.smtp.starttls.required: true
#    properties.mail.smtp.ssl.enable: true
#    default-encoding: utf-8
#    from: zgl4131025@gmail.com
    host: smtp.qq.com
    port: 587
    username: 786945363@qq.com
    password: ecegwozfzwngbcbh
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    default-encoding: UTF-8
  profiles:
    active: dev
mybatis:
  configuration:
    map-underscore-to-camel-case: true
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: ourchat的接口文档
  try-host: http://localhost:${server.port}
