server:
  port: 8000
netty:
  port: 8001
spring:
  datasource:
    username: root
    password: tomxun@2021
    url: jdbc:mysql://172.17.0.2:3306/chat?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ourchat
    # redis配置
  redis:
    database: 0
    host: 172.17.0.3
    port: 6379
    password: tomxun@redis
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
        min-idle: 2
    timeout: 6000
  mail:
    # 本地测试需要开启代理
    host: smtp.gmail.com
    username: zgl4131025@gmail.com
    password:
    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465
    properties.mail.display.sendmail: Javen
    properties.mail.display.sendname: Spring Boot Guide Email
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  rabbitmq:
    host: 172.17.0.5
    port: 5672
    username: admin
    password: admin
