server:
  port: 8088
netty:
  port: 8087
spring:
  datasource:
    username: root
    password: 54188
    url: jdbc:mysql://127.0.0.1:3306/chat?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ourchat
    # redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
        min-idle: 2
    timeout: 6000
  mail:
    host: smtp.qq.com
    port: 587
    username: 786945363@qq.com
    password: ecegwozfzwngbcbh
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    default-encoding: UTF-8
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
